### ISSUE TITLE
Identify the purpose of the site

### ISSUE THREAD

**Issue by williamthorsen** [williamthorsen/theme-park#1]
### Task

Discuss

- reasons for a theme park operator to have a website
- the people who might look at such a web site, and
- the reasons that they would be looking at the website

### Acceptance criteria

- [x] The purpose of the site is discussed
- [x] The discussion identifies why the theme park operator would want to have the site
- [x] The discussion identifies the intended users
- [x] The discussion identifies why the users would want to use the site
- [x] The purpose of the site is identified
- [x] The discussion is perceptive and documented

### Links

[Task instruction](https://www.coursera.org/learn/uol-web-development/supplement/ddRtW/2-4-2-team-assignment-part-1-task-instruction)
[Assignment](https://www.coursera.org/learn/uol-web-development/peer/wdmrv/2-4-3-team-assignment-part-1)

**Comment by williamthorsen** [comment]
Purpose of Website according to @Ywanggo:

> Our theme park website's goal is to give basic park information, assist guests with trip planning, attract more visitors to increase daily sales, and provide online buying alternatives. People of all ages are target clients, but parents and young family members will utilize our website to plan vacations, book tickets, and shop online in advance.

**Comment by williamthorsen** [comment]
I think this is a great summary of the purpose of the website. Maybe we could make the primary purpose more explicit:

> The purpose of the theme park website is to **increase the theme park's revenues** by giving basic information about the park, assisting guests with trip planning, ...

**Comment by williamthorsen** [comment]
Or maybe:

The theme park operator wants the website to increase the profits of his theme park. The website will facilitate this by giving basic park information, assisting guests ... etc.

**Comment by williamthorsen** [comment]
Other purposes we might mention:
- Make the theme park seem like an attractive destination
- Get users to subscribe to newsletters and promotions
- Use website usage  statistics to improve understanding of customers

**Comment by williamthorsen** [comment]
Why would users want to use the site? In addition to those mentioned in the purpose of the site:
- Learn about attractions at the park
- Learn about food and lodgings
- Learn about medical services at the park
- Learn about and subscribe to memberships and promotions
- Get help with technical issues, billing & membership issues, questions & answers

**Comment by williamthorsen** [comment]
Maybe define "intended users" more narrowly once we define the theme of the park.

**Comment by Ywanggo** [comment]
In case you didn't recive zipfile I sent on Slack, here is the zipfile for part1

[Stage1.zip](https://github.com/williamthorsen/theme-park/files/8968895/Stage1.zip)
