### ISSUE TITLE
Mark up wireframes with Appearance CSS

### ISSUE THREAD

**Issue by williamthorsen** [williamthorsen/theme-park#10]
### Task

Review the three wireframes that you produced for the large screen version of your web site from part 2 of the team project and add to them to ensure that they have the appearance that you wish your site to have.

Ensure that you have agreed the colours that will be applied to the elements. Agree the font family or specific font that you will use for different parts of your site, and the colours that should be used.

Work through the wireframes and decide on the correct CSS to build those pages, and add classes and identities to the pages. Mark up your wireframes accordingly. 

### Acceptance criteria

> We are looking for evidence of application of the various appearance and text styling CSS using the CSS Box Model.

- [ ] Classes and identities are added to the pages
- [ ] CSS rules based on semantic tags are used
- [ ] CSS rules based on CSS classes are used
- [ ] All styling comes from external stylesheets
- [ ] CSS rules set site-wide settings

#### Typography 

- [ ] Text is styled with CSS instructions
- [ ] Text styling is thoughtful
- [ ] Font family or specific font has been identified for different parts of the site
- [ ] Font selection is excellent, showing thought about the role of fonts
- [ ] All fonts have suitable fallbacks, especially where external fonts are loaded
- [ ] Consideration has been given to different roles of text on pages
- [ ] Function of text (e.g., anchors) remains clear

#### Colour

- [ ] Colours have been identified for all elements
- [ ] Use of colour is thoughtful
- [ ] Use of colour reflects the identified audience
- [ ] Use of colour reflects the page structure and imagery
- [ ] Colours are specified by component values
- [ ] More sophisticated aspects of colour, such as opacity, are used

### Links

[Task instruction](https://www.coursera.org/learn/uol-web-development/supplement/ozGFU/4-4-2-team-assignment-part-3-task-instruction)
[Assignment](https://www.coursera.org/learn/uol-web-development/peer/m9n6m/4-4-3-team-assignment-part-3)
