### ISSUE TITLE
Set up and link appearance stylesheet

### ISSUE THREAD

**Issue by williamthorsen** [williamthorsen/theme-park#11]
### Task

Code the CSS stylesheet with \[the appearance styling instructions\] and link them to the correct HTML elements using the class and id mechanism.

### Acceptance criteria

- [ ] The CSS appearance stylesheet has been created
- [ ] The stylesheet has an organized structure
- [ ] The stylesheet is referenced in the site's HTML pages

### Links

[Task instruction](https://www.coursera.org/learn/uol-web-development/supplement/ozGFU/4-4-2-team-assignment-part-3-task-instruction)
[Assignment](https://www.coursera.org/learn/uol-web-development/peer/m9n6m/4-4-3-team-assignment-part-3)
