### ISSUE TITLE
Upload Part 3 assignment to static web page system

### ISSUE THREAD

**Issue by williamthorsen** [williamthorsen/theme-park#12]
### Task

Upload your three new versions of HTML pages to the Workspace: static web page system in [week 10](https://www.coursera.org/learn/uol-web-development/ungradedLab/5zl6W/static-web-pages) with the class and id properties and the CSS stylesheet within a tidy directory structure.

Test that everything is working as expected by loading the pages in a browser using the shareable URL for your web site.

Validate the code in the pages using the [W3C code validator](https://validator.w3.org/)

### Acceptance criteria

- [ ] Tidy directory structure is used
- [ ] Pages have been uploaded
- [ ] Shareable link has been generated
- [ ] URL leads to the correct website
- [ ] W3C validation succeeds

### Links

[Task instruction](https://www.coursera.org/learn/uol-web-development/supplement/ozGFU/4-4-2-team-assignment-part-3-task-instruction)
[Assignment](https://www.coursera.org/learn/uol-web-development/peer/m9n6m/4-4-3-team-assignment-part-3)
[Static web page uploader](https://www.coursera.org/learn/uol-web-development/ungradedLab/5zl6W/static-web-pages)
