### ISSUE TITLE
Set up and link layout stylesheet

### ISSUE THREAD

**Issue by williamthorsen** [williamthorsen/theme-park#13]
### Task

Code the CSS stylesheet with the layout styling instructions and link them to the correct HTML elements using the class and id mechanism.

### Acceptance criteria

- [x] The CSS layout stylesheet has been created
- [x] The stylesheet has an organized structure
- [x] The stylesheet is referenced in the site's HTML pages

### Links

[Task instruction](https://www.coursera.org/learn/uol-web-development/supplement/2HhQn/5-4-2-team-assignment-part-4-task-instruction)
[Assignment](https://www.coursera.org/learn/uol-web-development/peer/29KDq/5-4-3-team-assignment-part-4)
