### ISSUE TITLE
Upload Part 4 assignment to static web page system

### ISSUE THREAD

**Issue by williamthorsen** [williamthorsen/theme-park#15]
### Task

Upload the .zip file of your three new versions of HTML pages to the Workspace: static web page system in [week 10]((https://www.coursera.org/learn/uol-web-development/ungradedLab/5zl6W/static-web-pages)) with the class and id properties and the CSS stylesheet within a tidy directory structure.

Test that everything is working as expected by loading the pages in a browser using the shareable URL for your web site.

Validate the code in the pages using the [W3C code validator](https://validator.w3.org/)

### Acceptance criteria

- [x] Tidy directory structure is used
- [x] Pages have been uploaded
- [x] Shareable link has been generated
- [x] URL leads to the correct website
- [ ] W3C validation succeeds
- [x] Website at the shared URL is identical to the website in the .zip file

### Links

[Task instruction](https://www.coursera.org/learn/uol-web-development/supplement/2HhQn/5-4-2-team-assignment-part-4-task-instruction)
[Assignment](https://www.coursera.org/learn/uol-web-development/peer/29KDq/5-4-3-team-assignment-part-4)
[Static web page uploader](https://www.coursera.org/learn/uol-web-development/ungradedLab/5zl6W/static-web-pages)
