### ISSUE TITLE
Install HTTP server to serve the site in development

### ISSUE THREAD

**Issue by williamthorsen** [williamthorsen/theme-park#18]
### Task

Install an HTTP server into the project so that the website can be viewed easily during development.

Some candidates:

- `http-server`
- `live-server`
- `lite-server`

### Acceptance criteria

- [x] The server package is specified in `package.json`
- [x] The `start` script runs the server, serving the pages from `./public/`
- [x] Use of the server is documented in the README
