### ISSUE TITLE
Agree on the content for the website

### ISSUE THREAD

**Issue by williamthorsen** [williamthorsen/theme-park#2]
### Task

Agree within the group the theme for your theme park and the types of attractions that you will have for the different visitors that you expect to come to your theme park.

Think of any other services that you will provide to visitors (for example food, access to money and medical help).

Think of any other information that people looking at your web site will want to know before they come and visit your theme park. Keep a record of the discussion in a document.

### Acceptance criteria

- [x] The team has discussed appropriate content
- [x] The discussion is meaningful and documented
- [x] The discussion improves the final product

### Links

[Task instruction](https://www.coursera.org/learn/uol-web-development/supplement/ddRtW/2-4-2-team-assignment-part-1-task-instruction)
[Assignment](https://www.coursera.org/learn/uol-web-development/peer/wdmrv/2-4-3-team-assignment-part-1)

**Comment by Ywanggo** [comment]
I documented stage1 content, will send you the zipfile I have.
