### ISSUE TITLE
Analyze 5 theme park sites

### ISSUE THREAD

**Issue by williamthorsen** [williamthorsen/theme-park#3]
### Task

As a group, choose five different web sites of theme parks.

Review the type of information that you find on the sites, and the structure that these sites have to help people find that information.

Make a list of the aspects of the sites that you think are a good idea or that work well, and a list of the aspects of the sites that you don't think are so successful. This will give you some insights that you can use when designing your own website.

Keep a record of the discussion in a document.

### Acceptance criteria

- [x] 5 theme park sites have been analyzed
- [x] The analysis is meaningful and documented
- [x] The analysis informs the design decisions

### Links

[Task instruction](https://www.coursera.org/learn/uol-web-development/supplement/ddRtW/2-4-2-team-assignment-part-1-task-instruction)
[Assignment](https://www.coursera.org/learn/uol-web-development/peer/wdmrv/2-4-3-team-assignment-part-1)
[Google Doc](https://docs.google.com/document/d/17um9FHZPbz1nFg9gFpvXhkc2dJhZUkomY1rPQD8Roxw/edit#heading=h.u7dfl65tcro3)

**Comment by williamthorsen** [comment]
## Analysis: Disneyland

Link: https://disneyland.disney.go.com/en-ca/

### Structure

- Navigation bar (with search tool and trip planner) giving quick access to sections of the site
- "Hero video" on the homepage to draw customers in
- Homepage sections leading to other areas of the site: travel planning, promotions, attractions, shopping
- Footer with links to specific areas of site content, help, social media, and related sites

### Information

- Descriptions of attractions and events
- Lots of information about various ticket options
- Lots of links to other sites (such as hotels and Disney+)
- Trip planner


### Pros
I think the main page **works very well**. Navigation bar, search tool, and footer are basically needed for any site. Besides that:

The video on the main page isn't the best, but it does capture some of the magic of the park, and it promotes an attraction ("Night-time spectaculars")

The section overviews ("Reservation and Planning Guide") are excellent: They have attractive photos and tasteful formatting, and they give easy access to the main things a customer might be looking for.

The drop-down menus are tasteful and well-designed.

### Cons

Some areas of the site (such as the [Theme Parks page](https://disneyland.disney.go.com/en-ca/experience-updates/parks/)) are **very heavy** on text -- more than most people would want to read. It could be organized better for skimming.

The text is **very small** in some places.

Some people find "hover" menus difficult to work with.

Navigation is slow.

Some links unexpectedly lead to different Disney sites.

**Comment by williamthorsen** [comment]
## Analysis: Canada's Wonderland

Link: https://www.canadaswonderland.com

### Structure

- Very few major sections (tickets, rides, park info)
- Pages for searching and filtering (restaurants, rides, events)
- Dedicated pages for the major rides
- Database-style pages for events
 
### Information

- Information on why the park is a good place to visit (families, corporate events, etc.)
- Descriptions of all rides, including important details such as "thrill level"
- Special events and promotions
- Trip planner

### Pros

Simple navigation bar (only three sections) means that finding the most important information is quite easy.

### Cons

Lots of information. Content overlap can be confusing, and finding what you want isn't always easy.

Trip planner makes it easier for users to think about making a trip.

**Comment by williamthorsen** [comment]
## Analysis: Universal Orlando

Link: https://www.universalorlando.com/web/en/us

### Structure

* Large "hero" image on most pages, footer at the bottom
* Collapsible menu with only two icons (cart and search) in the nav bar
* Structured mainly around how things are sold: ride tickets, vacation packages, hotels, etc., which appear in a list of "cards" (similar to hotel sites) on a page with not much more than a category heading
* Secondary structure: Separate "park details" page for each theme park (these pages are more like the main pages of the other sites analyzed)
* Separate "attraction" page for each attraction at a theme park
* Merchandise shop

Note that the easiest way to get an idea of the structure is to use the collapsible menu.

### Information

* Most information is sales information
* Details about attractions, hotels, etc., but not much
* Safety guidelines

This site has much less text than the Disneyland site.

### Pros

* Easy to use if you are familiar with hotel or flight booking sites
* Layout is simple
* Content is skimmable, good use of headings, not much text to read

### Cons

* Not much detailed information (about attractions, hotels, etc.), which might disappoint some users
* Navigation can be confusing (breadcrumbs help, but they are subtle)
* Boring layout with very generic styling
