### ISSUE TITLE
Design wireframes

### ISSUE THREAD

**Issue by williamthorsen** [williamthorsen/theme-park#4]
### Task

Produce a set of wireframes for the site, showing the concepts for both a wide screen and small screen. These can either be drawn by hand or produced using a tool such as PowerPoint or a graphics package such as Illustrator.

Avoid painting or photo-editing software such as Paint or Photoshop as designs produced in this way are difficult to edit.

Ensure that the designs are clear and easy to read.

### Acceptance criteria

- [x] Wireframes have been created
- [x] Wireframes serve as a clear model for the website
- [x] Wireframes show appropriate level of planning and detail, i.e.,
  - [x] not vague
  - [x] not too specific (clearly created from the finished pages)
- [ ] Changes to designs are clearly shown

### Links

[Task instruction](https://www.coursera.org/learn/uol-web-development/supplement/ddRtW/2-4-2-team-assignment-part-1-task-instruction)
[Assignment](https://www.coursera.org/learn/uol-web-development/peer/wdmrv/2-4-3-team-assignment-part-1)

**Comment by williamthorsen** [comment]
Uploaded in #24.
