### ISSUE TITLE
Agree on the structure of the website

### ISSUE THREAD

**Issue by williamthorsen** [williamthorsen/theme-park#5]
### Task

Agree within your group the structure of your web site, with the aim of designing a web site with 3 pages.

What information will appear on the main page, and what will appear on the other two pages?

Think about how you might present the content, and whether you will have semantic parts such as asides or pop-up windows.

Keep a record of the discussion in a document.

### Acceptance criteria

- [x] Structure is discussed and agreed on
- [x] Discussion is clear and documented
- [x] Discussion results in improved final product

### Links

[Task instruction](https://www.coursera.org/learn/uol-web-development/supplement/ddRtW/2-4-2-team-assignment-part-1-task-instruction)
[Assignment](https://www.coursera.org/learn/uol-web-development/peer/wdmrv/2-4-3-team-assignment-part-1)

**Comment by williamthorsen** [comment]
Rationale for the directory structure is documented in the `directory-structure.md` doc.

**Comment by williamthorsen** [comment]
Done in #22 and #23.
