### ISSUE TITLE
Markup wireframes with HTML

### ISSUE THREAD

**Issue by williamthorsen** [williamthorsen/theme-park#6]
### Task

Review the three wireframes that you produced for the large screen version of your web site from part 1 of the team project and make any changes that you think would improve them.

Work through the wireframes and decide on the correct HTML to build those pages. Think carefully about the use of layout tags such as tables, and only use them where content is really a table. 

Make sure that all the parts of the pages have a semantic identity, either by using existing semantic tags or by defining "div" tags for the content.

Attempt to use a range of the various formatting tags available to add richness and extra meaning to your content. Consider how different media can add to the way that your pages communicate information.

Mark up your wireframes with the HTML tags that you intend to use. Upload these marked-up wireframes in a .zip file into the Workspace: static web pages that is located in the end of week 10 and generate a shareable URL. Consider how your HTML supports the use of your pages by users with disabilities.

### Acceptance criteria

- [x] Semantic tags are used and are always appropriate
- [x] All (or almost all) significant semantic spaces in the pages are defined semantically
- [x] All (or almost all) content is contained in a block whose purpose is identifiable

[Task instruction](https://www.coursera.org/learn/uol-web-development/supplement/Wpldi/3-4-2-team-assignment-part-2-task-instruction)
[Assignment](https://www.coursera.org/learn/uol-web-development/peer/HnFDm/3-4-3-team-assignment-part-2)

**Comment by williamthorsen** [comment]
## Home page

![Image](https://user-images.githubusercontent.com/26130675/174400011-19413720-7d9f-4a64-a615-c6474d9ea310.jpg)

**Comment by williamthorsen** [comment]
## Attraction page

![Image](https://user-images.githubusercontent.com/26130675/174400044-8598b89b-854b-4538-ae32-022881bf52f3.jpg)

**Comment by williamthorsen** [comment]
## Shop page

![Image](https://user-images.githubusercontent.com/26130675/174400078-9e36d0eb-370c-453a-80ab-78a5190d95fa.jpg)

**Comment by williamthorsen** [comment]
## Home page v2

![Image](https://user-images.githubusercontent.com/26130675/174914123-e7f33899-ab27-499c-89e6-69e009a83f31.png)

**Comment by williamthorsen** [comment]
## Attraction page v2

![Image](https://user-images.githubusercontent.com/26130675/174914167-5d8c0a3f-66a1-4f2b-8727-4c761b65ae6c.png)

**Comment by williamthorsen** [comment]
## Shop page v2

![Image](https://user-images.githubusercontent.com/26130675/174914222-87e61f0a-8f9b-4878-8898-929d94b34da5.png)
