### ISSUE TITLE
Code HTML pages

### ISSUE THREAD

**Issue by williamthorsen** [williamthorsen/theme-park#7]
### Task

Code the three pages in HTML and enter in some essential text content that you write yourself. Name the main/first page of your web site: index.html. Ensure that you use comments to help all the coders to understand the code.

Find some pictures and any other media that you consider appropriate and embed them into the pages using the correct HTML tags. Ensure that your code includes comments to help you work with the code and quickly relate it to the wireframes. It could be helpful to include comments to indicate who contributed chunks of the code so that you can ensure you can work together as a team.

### Acceptance criteria

> We are looking for a well constructed skeleton that reflects the design in the wireframes and for content that is relevant and appropriate.

- [x] A wide range of different elements are used
- [x] Appropriate semantic tags are used, including
  - [x] use of predefined tags
  - [x] use of div block tags
  - [x] no use of deprecated elements (such as `<center>`)
- [x] Both structuring and media elements are used
- [ ] HTML is richly commented
- [ ] HTML supports accessibility, particularly in use of media tags

### Links

[Task instruction](https://www.coursera.org/learn/uol-web-development/supplement/Wpldi/3-4-2-team-assignment-part-2-task-instruction)
[Assignment](https://www.coursera.org/learn/uol-web-development/peer/HnFDm/3-4-3-team-assignment-part-2)

**Comment by williamthorsen** [comment]
See the Yale guide: [Usability and Accessibility > Images](https://usability.yale.edu/web-accessibility/articles/images)
