### ISSUE TITLE
Upload Part 1 assignment to static web page system

### ISSUE THREAD

**Issue by williamthorsen** [williamthorsen/theme-park#8]
### Task

Upload in the .zip file your three pages within a tidy directory structure to the **Workspace: static web pages** that is located in the [end of week 10](https://www.coursera.org/learn/uol-web-development/ungradedLab/5zl6W/static-web-pages).

Update your shareable link and load the pages in a browser using the shareable URL.

Validate the code in the pages using the [W3C code validator](https://validator.w3.org/)

### Acceptance criteria

- [x] Tidy directory structure is used
- [x] Pages have been uploaded
- [x] Shareable link has been generated
- [x] URL leads to the correct website
- [ ] W3C validation succeeds

### Links

[Task instruction](https://www.coursera.org/learn/uol-web-development/supplement/ddRtW/2-4-2-team-assignment-part-1-task-instruction)
[Assignment](https://www.coursera.org/learn/uol-web-development/peer/wdmrv/2-4-3-team-assignment-part-1)
[Static web page uploader](https://www.coursera.org/learn/uol-web-development/ungradedLab/5zl6W/static-web-pages)

**Comment by Ywanggo** [comment]
https://hub.labs.coursera.org:443/connect/sharedtuinrnun?forceRefresh=false&path=%2F
this is the link I generated based on your framework and I also uploaded the pictures for our webpage.

**Comment by Ywanggo** [comment]
[Part2v2.zip](https://github.com/williamthorsen/theme-park/files/8968864/Part2v2.zip)

There is the zip file I uploaded to week10 link generate pages.
However, there are several errors showing up on the W3C validation pages. Would you mind to have a look? I don't quit understand how to solve these errors.


![Image](https://user-images.githubusercontent.com/49178843/175343281-6449deea-69da-4b42-8a1f-61b6a6a0048e.png)
