### ISSUE TITLE
Upload Part 2 assignment to static web page system

### ISSUE THREAD

**Issue by williamthorsen** [williamthorsen/theme-park#9]
### Task

Upload in the .zip file your three pages within a tidy directory structure to the **Workspace: static web pages** that is located in the [end of week 10](https://www.coursera.org/learn/uol-web-development/ungradedLab/5zl6W/static-web-pages).

Update your shareable link and load the pages in a browser using the shareable URL.

Validate the code in the pages using the [W3C code validator](https://validator.w3.org/)

### Acceptance criteria

- [ ] Tidy directory structure is used
- [ ] Pages have been uploaded
- [ ] Shareable link has been generated
- [ ] URL leads to the correct website
- [ ] W3C validation succeeds

### Links

[Task instruction](https://www.coursera.org/learn/uol-web-development/supplement/Wpldi/3-4-2-team-assignment-part-2-task-instruction)
[Assignment](https://www.coursera.org/learn/uol-web-development/peer/HnFDm/3-4-3-team-assignment-part-2)
[Static web page uploader](https://www.coursera.org/learn/uol-web-development/ungradedLab/5zl6W/static-web-pages)
